table dim_customer
	lineageTag: 32cf9856-2332-4e2d-92fa-2ac1f0b1a71e
	sourceLineageTag: [dbo].[dim_customer]

	measure 'Total Customers' =
			
			COUNTROWS(dim_customer)
		formatString: 0
		lineageTag: c5c43bcc-4d17-4e52-a0b2-b83fb6883ecb

		changedProperty = Name

	measure 'Average Credit Score' =
			
			AVERAGE(dim_customer[credit_score])
		lineageTag: 459682f0-695f-4b7f-bb40-a189e822bc8b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Debt' =
			
			SUM(dim_customer[debt])
		lineageTag: 736fdd61-1113-4ca9-a3a2-5eca5bf3c590

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Income' =
			
			AVERAGE(dim_customer[income])
		lineageTag: 27ca8b0f-aac0-4278-9594-31cf583c15b1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'High Risk Customers' =
			
			CALCULATE(
			    COUNTROWS(dim_customer),
			    dim_customer[credit_score] < 650
			)
		formatString: 0
		lineageTag: d2390d17-250c-4c99-b0a1-c320dec14e0e

		changedProperty = Name

	column customer_key
		dataType: int64
		formatString: 0
		lineageTag: 03c85e0a-ce30-48f1-aadb-ee558d2ecd0d
		sourceLineageTag: customer_key
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column current_age
		dataType: int64
		formatString: 0
		lineageTag: b03ee9d3-07b4-4e3c-8040-1682a28e4e84
		sourceLineageTag: current_age
		summarizeBy: none
		sourceColumn: current_age

		annotation SummarizationSetBy = Automatic

	column retirement_age
		dataType: int64
		formatString: 0
		lineageTag: bf267a89-2919-4a00-8109-87667de2f673
		sourceLineageTag: retirement_age
		summarizeBy: none
		sourceColumn: retirement_age

		annotation SummarizationSetBy = Automatic

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: 29d0adad-1c66-4df8-b3ef-ec663a8814f7
		sourceLineageTag: birth_year
		summarizeBy: none
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column birth_month
		dataType: int64
		formatString: 0
		lineageTag: afaeeca2-afb5-4255-a8a8-29e722034072
		sourceLineageTag: birth_month
		summarizeBy: none
		sourceColumn: birth_month

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 69b5444f-40de-4db3-a8a8-cc274678e94e
		sourceLineageTag: gender
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column per_capita_income
		dataType: double
		lineageTag: 126cc301-60eb-4e3f-8314-0737034f8604
		sourceLineageTag: per_capita_income
		summarizeBy: none
		sourceColumn: per_capita_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Income
		dataType: double
		lineageTag: 1f5593f8-0f18-4b50-91af-5b8f173b9646
		sourceLineageTag: Income
		summarizeBy: none
		sourceColumn: Income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debt
		dataType: double
		lineageTag: 82a64eaf-1ec4-4e50-8cdc-7b98feec7eae
		sourceLineageTag: debt
		summarizeBy: none
		sourceColumn: debt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_score
		dataType: int64
		formatString: 0
		lineageTag: 71e81fa7-ebf5-46c3-9348-3299e3601547
		sourceLineageTag: credit_score
		summarizeBy: none
		sourceColumn: credit_score

		annotation SummarizationSetBy = Automatic

	column number_of_cards
		dataType: int64
		formatString: 0
		lineageTag: db120079-0193-4431-80d4-481570a64f63
		sourceLineageTag: number_of_cards
		summarizeBy: none
		sourceColumn: number_of_cards

		annotation SummarizationSetBy = Automatic

	partition dim_customer = entity
		mode: directLake
		source
			entityName: dim_customer
			schemaName: dbo
			expressionSource: 'DirectLake - fabric_banking_medallion_lakehouse'

