table dim_customer
	lineageTag: 3ef94c35-12fc-4a7d-84b6-bd1cb8051cd7
	sourceLineageTag: 32cf9856-2332-4e2d-92fa-2ac1f0b1a71e

	measure 'Total Customers' = EXTERNALMEASURE("Total Customers", INTEGER, "DirectQuery to AS - sm_gold_analytics")
		formatString: 0
		lineageTag: fab323c8-a1cd-4500-ab28-4b18433e84c1
		sourceLineageTag: c5c43bcc-4d17-4e52-a0b2-b83fb6883ecb
		dataCategory: Uncategorized

	measure 'Average Credit Score' = EXTERNALMEASURE("Average Credit Score", DOUBLE, "DirectQuery to AS - sm_gold_analytics")
		lineageTag: d041775b-852d-4875-9d13-c687f268f419
		sourceLineageTag: 459682f0-695f-4b7f-bb40-a189e822bc8b
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Debt' = EXTERNALMEASURE("Total Debt", DOUBLE, "DirectQuery to AS - sm_gold_analytics")
		lineageTag: 18219f4c-ab42-4ea4-8e5d-6914495a42ea
		sourceLineageTag: 736fdd61-1113-4ca9-a3a2-5eca5bf3c590
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Income' = EXTERNALMEASURE("Average Income", DOUBLE, "DirectQuery to AS - sm_gold_analytics")
		lineageTag: ef8119b4-5518-4d8b-aae7-da063b986940
		sourceLineageTag: 27ca8b0f-aac0-4278-9594-31cf583c15b1
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'High Risk Customers' = EXTERNALMEASURE("High Risk Customers", INTEGER, "DirectQuery to AS - sm_gold_analytics")
		formatString: 0
		lineageTag: b2a741f9-4dae-40fb-b897-a306f0694bb1
		sourceLineageTag: d2390d17-250c-4c99-b0a1-c320dec14e0e
		dataCategory: Uncategorized

	column customer_key
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: 45b03c82-8205-4011-8ea0-fd5e25931c3e
		sourceLineageTag: 03c85e0a-ce30-48f1-aadb-ee558d2ecd0d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = User

	column current_age
		dataType: int64
		formatString: 0
		lineageTag: a1c5a9f1-7b4a-4cd9-b4be-a9ead6496890
		sourceLineageTag: b03ee9d3-07b4-4e3c-8040-1682a28e4e84
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: current_age

		annotation SummarizationSetBy = User

	column retirement_age
		dataType: int64
		formatString: 0
		lineageTag: 41407235-dee5-4fb1-971d-24ea216a696c
		sourceLineageTag: bf267a89-2919-4a00-8109-87667de2f673
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: retirement_age

		annotation SummarizationSetBy = User

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: 73547a64-ef11-448c-9243-bb9f8e341b06
		sourceLineageTag: 29d0adad-1c66-4df8-b3ef-ec663a8814f7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: birth_year

		annotation SummarizationSetBy = User

	column birth_month
		dataType: int64
		formatString: 0
		lineageTag: 10d9ec02-97ae-4526-9bc3-8b29c5c22456
		sourceLineageTag: afaeeca2-afb5-4255-a8a8-29e722034072
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: birth_month

		annotation SummarizationSetBy = User

	column gender
		dataType: string
		lineageTag: 3ecf565a-ab76-4c6f-a74c-a79c6a3e61da
		sourceLineageTag: 69b5444f-40de-4db3-a8a8-cc274678e94e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = User

	column per_capita_income
		dataType: double
		lineageTag: 6895249e-614a-4e56-8be4-96060b2b6ba4
		sourceLineageTag: 126cc301-60eb-4e3f-8314-0737034f8604
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: per_capita_income

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Income
		dataType: double
		lineageTag: 63f01356-084c-418e-8c3b-affda693dec0
		sourceLineageTag: 1f5593f8-0f18-4b50-91af-5b8f173b9646
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Income

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debt
		dataType: double
		lineageTag: 01abcbdc-93ca-402a-95c8-0fb842497268
		sourceLineageTag: 82a64eaf-1ec4-4e50-8cdc-7b98feec7eae
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: debt

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_score
		dataType: int64
		formatString: 0
		lineageTag: 9977c35c-7ea8-4a7f-a5f8-4b70145681d6
		sourceLineageTag: 71e81fa7-ebf5-46c3-9348-3299e3601547
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: credit_score

		annotation SummarizationSetBy = User

	column number_of_cards
		dataType: int64
		formatString: 0
		lineageTag: 0926ac49-907a-4d3d-ba97-ac2640ca8690
		sourceLineageTag: db120079-0193-4431-80d4-481570a64f63
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: number_of_cards

		annotation SummarizationSetBy = User

	partition dim_customer = entity
		mode: directQuery
		source
			entityName: dim_customer
			expressionSource: 'DirectQuery to AS - sm_gold_analytics'

